services:
  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - docker-network

  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    ports:
      - "5000:5000"

networks:
  docker-network:
    driver: bridge
