services:
  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    ports:
      - "5000:5000"
