services:
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    networks:
      - docker-network

  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    ports:
      - "5000:5000"

networks:
  docker-network:
    driver: bridge
